### ISSUE TITLE
[Bug] SSL Error

### ISSUE THREAD

**Issue by YuzuRyo61** [YuzuRyo61/Misskey.py#2]
# sammary
SSLCertificate

Tried address: msk.kikurage.net
*This server is certificate from Cloudflare*

# trace

```
Traceback (most recent call last):
  File "C:\Python-37x64\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python-37x64\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Python-37x64\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Python-37x64\lib\site-packages\urllib3\connection.py", line 356, in connect
    ssl_context=context)
  File "C:\Python-37x64\lib\site-packages\urllib3\util\ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python-37x64\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Python-37x64\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Python-37x64\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python-37x64\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python-37x64\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python-37x64\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='msk.kikurage.net', port=443): Max retries exceeded with url: /api/meta (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python-37x64\lib\site-packages\Misskey\Misskey.py", line 69, in __init__
    self.res = requests.post(self.instanceAddressApiUrl + "/meta")
  File "C:\Python-37x64\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python-37x64\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python-37x64\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python-37x64\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python-37x64\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='msk.kikurage.net', port=443): Max retries exceeded with url: /api/meta (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)')))
```

**Comment by YuzuRyo61** [comment]
v1.0.0で仕様変更とかでちょっとこのIssueについては目をつぶることに
